---
- name: Deploy Prescripto Application
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Stop Existing Containers
      shell: docker compose down
      args:
        chdir: /mnt/c/ProgramData/Jenkins/.jenkins/workspace/prescripto-project
      ignore_errors: yes

    - name: Build and Start Containers
      shell: docker compose up --build -d
      args:
        chdir: /mnt/c/ProgramData/Jenkins/.jenkins/workspace/prescripto-project